# Generated by Django 5.2.1 on 2025-05-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='is_author',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
    ]
