# Generated by Django 5.2.1 on 2025-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_guest',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_author',
            field=models.BooleanField(default=True),
        ),
    ]
