# Generated by Django 5.2.1 on 2025-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_alter_blogpost_content_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
